### ISSUE TITLE
Remaining tasks

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-node-debug2#42]
* SourceMaps
  - [x] Smart code stepping - Microsoft/vscode-chrome-debug-core#34
  - [x] Support "dynamically generated sourcemaps" and SystemJS - Microsoft/vscode-chrome-debug-core#36

* Misc
  - [x] completionRequest (intellisense for debug console) - Microsoft/vscode-chrome-debug-core#87
  - [x] ~~Support a UI picker of all available targets - Microsoft/vscode-chrome-debug-core#19~~
  - [x] ~~extension host support - #4~~
  - [ ] Localization - Microsoft/vscode-chrome-debug-core#37
  - [x] Port provideInitialConfigurations from vscode-node-debug - #18

* Bugs
  - [x]  Should return "not available" instead of "ReferenceError" - #31
  - [x] Locals window visualization not updated properly - #30

* Engineering
  - [x] Write more E2E tests
  - [x] Audit unit test coverage vs e2e test coverage and improve coverage
  - [x] Travis job to run E2E tests against different versions of Node
  - [x] Build against a .d.ts generated from the protocol.json - https://github.com/Microsoft/vscode-chrome-debug-core/issues/80
  - [x] Travis job to build against different versions of the protocol.json

* ?
  - [ ] Surface async callstacks - #13

**Comment by auchenberg** [comment]
You could use the new Projects feature for this, https://github.com/Microsoft/vscode-node-debug2/projects

**Comment by roblourens** [comment]
I like this better because I can link to issues in different repos and break things into arbitrary lists.

**Comment by auchenberg** [comment]
🎉🎈👌🏻
