### ISSUE TITLE
Node CDP Debug tasks

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-node-debug2#7]
**P0**
* Startup:
  - [x] no "launch" support - #2
  - [x] no "restart" on attach - #3 
  - [x] early breakpoints on startup don't work because debugger does not break on entry by default - #5
 - [x] Process lifecycle - #8, #9 
* Variables:
  - [x] properties with getters not supported - Microsoft/vscode-chrome-debug-core#77
  - [x] array sorting wrong (alphabetically instead of numerical) - Microsoft/vscode-chrome-debug-core#62
  - [x] large arrays slow: no paging ('chunks')
     (needs adoption of VS Code variables paging) - Microsoft/vscode-chrome-debug-core#4
  - [x] no Map support - Microsoft/vscode-chrome-debug-core#31
  - [x] no Set support - Microsoft/vscode-chrome-debug-core#31
* Source Maps:
  - [x] no inlined sources - Microsoft/vscode-chrome-debug-core#85
  - [x] no remote source maps
 - [x] Resolve sourcemaps before scripts are loaded - Microsoft/vscode-chrome-debug-core#47
* Misc
  - [x] no local/remote mapping for remote debugging - Microsoft/vscode-chrome-debug-core#86
  - [x] Don't hang on to the request when breakpoints don't bind - Microsoft/vscode-chrome-debug-core#38

**P1**
* Variables
  - [x] setting variable values - Microsoft/vscode-chrome-debug-core#58
  - [x] Show generator state - Microsoft/vscode-chrome-debug-core#32
  - [x] Show Promise state - Microsoft/vscode-chrome-debug-core#33
* SourceMaps
  - [ ] Smart code stepping - Microsoft/vscode-chrome-debug-core#34
* Misc
  - [x] ~~Support function breakpoints - Microsoft/vscode-chrome-debug-core#28~~
  - [x] ~~Support callstack paging - Microsoft/vscode-chrome-debug-core#30~~
  - [x] Show variable type on hover - Microsoft/vscode-chrome-debug-core#52
  - [x] Add support for conditional breakpoints - Microsoft/vscode-chrome-debug-core#10
  - [x] Minor refactoring to support some features - Microsoft/vscode-chrome-debug-core#57

**P2**
* Startup
  - [ ] Support a UI picker of all available targets - Microsoft/vscode-chrome-debug-core#19
  - [x] Support runInTerminalRequest - #6
 - [x] Support noDebug parameter - Microsoft/vscode-chrome-debug#89
* SourceMaps
  - [ ] Support "dynamically generated sourcemaps" and SystemJS - Microsoft/vscode-chrome-debug-core#36
* Misc
  - [ ] completionRequest (intellisense for debug console) - Microsoft/vscode-chrome-debug-core#87
  - [x] Stop using deprecated 'lines' prop on SetBreakpointsArguments from vscode-debugprotocol - Microsoft/vscode-chrome-debug-core#73

**Engineering**
- [x] Get existing Node tests working against this debug adapter
- [x] Do a pass for error messages and failure modes that are handled in node-debug but not here
- [x] Launch error experience - #14
- [x] Cleanup properly after running in server mode - Microsoft/vscode-chrome-debug-core#95
- [x] Switch to ES6 output - Microsoft/vscode-chrome-debug-core#100
- [x] List in the marketplace (as a built-in)
- [x] Include in the code-insiders build

**Later**
  - [ ] no extension host support - #4 
  - [ ] Localization - Microsoft/vscode-chrome-debug-core#37

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode-node-debug2/issues/42
